-   id: docker-hook
    name: Docker test hook
    entry: echo
    language: docker
    files: \.txt$

-   id: docker-hook-arg
    name: Docker test hook
    entry: echo -n
    language: docker
    files: \.txt$

-   id: docker-hook-failing
    name: Docker test hook with nonzero exit code
    entry: bork
    language: docker
    files: \.txt$
