-   id: echo-entrypoint
    name: echo (via --entrypoint)
    language: docker_image
    entry: --entrypoint echo cogniteev/echo
-   id: echo-cmd
    name: echo (via cmd)
    language: docker_image
    entry: cogniteev/echo echo
